title: Suhas S
logo: /assets/img/suhas_photo.jpg
description: Electronics and Instrumentation Engineering Graduate working for Infosys Limited as a SAP SD Consultant.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
